name: Build

on:
  push:
    branches: web-revamp

jobs:

  build-web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Create Container
        working-directory: Oxygen/sonic3air/build/_emscripten/
        run: |
          docker build -t emscripten_gl .
          mkdir build
      - name: Build
        run: |
          docker run --rm -v $(pwd):/src -u $(id -u):$(id -g) --name sonic3air_build emscripten_gl /bin/bash -c "cd Oxygen/sonic3air/build/_emscripten/build; emmake cmake -DCMAKE_BUILD_TYPE=Release ..; emmake cmake --build ."
