name: Build

on:
  push:
    branches: web-revamp

jobs:

  build-web:
    runs-on: ubuntu-latest

    steps:
      - name: Create Container
        working-directory: ./Oxygen/sonic3air/build/_emscripten/
        run: |
          docker build -t emscripten_gl .
